spring.application.name=20260706_csc340-01_dan-valcour_assignment3

spring.datasource.url={SPRING_DATASOURCE_URL}
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE