<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wurm Online Creatures</title>
  <link rel="stylesheet" type="text/css" href="/style.css">
</head>

<body>
  <header>
    <div>
      <h1>Wurm Online Creatures</h1>
      <nav>
        <div>
          <a href="/characters">Home</a>
        </div>
        <div>
          <a href="/characters/about">About</a>
        </div>
        <div>
          <a href="/characters/new">Add a Creature</a>
        </div>
      </nav>
    </div>
  </header>

  <article class="about">
    <h2>About This Site</h2>
    <div class="about-content">
      <div class="image-column">
        <img src="/content/meditation.jpg" alt="A meditating player">
        <img src="/content/bridges.jpg" alt="A bridge">
        <img src="/content/combat.jpg" alt="Soldiers preparing for battle">
        <img src="/content/digging.jpg" alt="A terreforming project">
      </div>
      <div class="about-center">
        <p class="about-text">
          Wurm Online is a multiplayer sandbox game that was created by Mojang AB in 2003, and it was later acquired by
          Code Club AB. It is one of the first
          successful massively multiplayer sandbox games
          with 3D graphics, and is notable for having terrain and buildings that are fully modifiable by
          players. This was quite a technical achievement at
          the time, especially since the game was capable of hosting hundreds of players on a single server. Wurm
          Online's
          servers have remained active for over 20 years,
          and it has remained a niche game with a small but loyal communhity. Markus Persson, one of the original
          developers of Wurm Online, eventually left the
          project and moved on to find tremendous success when he created Minecraft in 2009. This website contains a
          searchable list of creatures found in the game
          Wurm Online.
        </p>
        <h2>Disclaimer</h2>
        <p>
          This website is created for demonstration purposes only. Wurm Online and all associated artwork are property
          of Code Club AB.
        </p>
        <img class="panorama" src="/content/panorama.jpeg" alt="Panoramic view">
      </div>
      <div class="image-column">
        <img src="/content/mining.jpg" alt="A mine">
        <img src="/content/trade.jpg" alt="A cart of goods">
        <img src="/content/ships.jpg" alt="A ship">
        <img src="/content/unicorn.jpg" alt="A unicorn">
      </div>
    </div>
  </article>

  <footer>
    <div>
      <p>Site created by Daniel Valcour (<a href="https://github.com/jmandevel">jmandevel</a>) (<a
          href="https://github.com/jmandevel/20260706_csc340-01_dan-valcour_assignment3">Source Code</a>)</p>
    </div>
  </footer>
</body>

</html>