<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wurm Online Creatures</title>
  <link rel="stylesheet" type="text/css" href="/style.css">
</head>

<body>
  <header>
    <div>
      <h1>Wurm Online Creatures</h1>
      <nav>
        <div>
          <a href="index.html">Home</a>
        </div>
        <div>
          <a href="about.html">About</a>
        </div>
        <div>
          <a href="new-character-form.html">Add a Creature</a>
        </div>
      </nav>
    </div>
  </header>

  <main class="about">
    <article class="creature-description">
      <h2>Brown Bear</h2>
      <img src="/content/Brownbear.jpg" alt="Brown Bear">
      <blockquote class="ingame-quote"><em>The brown bear has a distinctive hump on the shoulders, and long deadly claws
          on the front paws.</em> - ingame description
      </blockquote>
      <h3>General Info</h3>
      <p>
        Brown bears are dangerous wild animals that can be found roaming the lands of Wurm. They are carnivorous,
        meaning they will eat other creatures and players if they have the chance. They are capable of swimming, so
        players cannot excape an aggressive brown bear by jumping into a water. Butchering a slain brown bear
        produces meat, fur, and bear teeth, which can be used in crafting. With level 60 animal taming level, players
        can tame brown bears and keep them as pets. They can be a useful companion when facing off against hostile
        wildlife. Players with level 23 body control can ride tamed brown bears as a mount.
      </p>
    </article>
  </main>

  <footer>
    <div>
      <p>Site created by Daniel Valcour (<a href="https://github.com/jmandevel">jmandevel</a>) (<a
          href=https://github.com/jmandevel/creature-site>Source Code</a>)</p>
    </div>
  </footer>
</body>

</html>