<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wurm Online Creatures</title>
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>

<body>
    <header>
        <div>
            <h1>Wurm Online Creatures</h1>
            <nav>
              <div>
                <a href="index.html">Home</a>
              </div>
              <div>
                <a href="about.html">About</a>
              </div>
              <div>
                <a href="new-character-form.html">Add a Creature</a>
              </div>
            </nav>
        </div>
    </header>

<search>
    <div class="search-bar">
        <input type="" text" class="search" placeholder="Search creatures...">
        <button>Search</button>
    </div>
    <div class="filters">
        <button class="filter filter-active">Valreian</button>
        <button class="filter">Wurmian</button>
        <button class="filter">Avatar</button>
        <button class="filter">Spider</button>
        <button class="filter">Passive</button>
        <button class="filter">Aggressive</button>
    </div>
    </search>

    <main class="card-container">
        <div class="card">
            <img src="/content/brown-bear.png" alt="Brown Bear">
            <h2>Brown Bear</h2>
            <p class="origin"><strong>Origin:</strong> Wurm</p>
            <p class="description">The brown bear has a distinctive hump on the shoulders, and long deadly claws on the front paws.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/dog.png" alt="Dog">
            <h2>Dog</h2>
            <p class="origin"><strong>Origin:</strong> Wurm</p>
            <p class="description">Occasionally this dog will bark and scratch itself behind the ears.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/huge-spider.png" alt="Huge Spider">
            <h2>Huge Spider</h2>
            <p class="origin"><strong>Origin:</strong> Wurm</p>
            <p class="description">Monstrously huge and fast, these spiders love to be played with.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/lava-spider.png" alt="Lava Spider">
            <h2>Lava Spider</h2>
            <p class="origin"><strong>Origin:</strong> Wurm</p>
            <p class="description">Lava spiders usually lurk in their lava pools, catching curious prey.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/deathcrawler.png" alt="Deathcrawler Minion">
            <h2>Deathcrawler</h2>
            <p class="origin"><strong>Origin:</strong> Valrei</p>
            <p class="description">The Deathcrawler minions usually spawn in large numbers. They have deadly poisonous bites. </p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/nogump.png" alt="Son of Nogump">
            <h2>Son of Nogump</h2>
            <p class="origin"><strong>Origin:</strong> Valrei</p>
            <p class="description">Nogump the dirty has given birth to this foul two-headed giant wielding a huge two handed sword.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/magranon.png" alt="Avatar of Magranon">
            <h2>Magranon</h2>
            <p class="origin"><strong>Origin:</strong> Valrei</p>
            <p class="description">A ferocious beast indeed, the juggernaut can crush mountains with its horned forehead.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
        <div class="card">
            <img src="/content/fo.png" alt="Avatar of Fo">
            <h2>Fo</h2>
            <p class="origin"><strong>Origin:</strong> Valrei</p>
            <p class="description">A towering giant composed of vines and roots. It gives off an aura of peace.</p>
            <a href="details.html"><button>More Info</button></a>
        </div>
    </main>

    <footer>
        <div>
            <p>Site created by Daniel Valcour (<a href="https://github.com/jmandevel">jmandevel</a>) (<a href="https://github.com/jmandevel/creature-site">Source Code</a>)</p>
        </div>
    </footer>
</body>

</html>